{{- if .Values.postgres.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "customer.fullname" . }}-postgres
  labels:
    {{- include "customer.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USERNAME: {{ .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
{{- end }}
