services:
  # Pipeline
  kafka:
    image: apache/kafka-native:latest
    # ports:
    #   - "9092:9092"
    environment:
      # Listeners for host and docker communication
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT
      # KRaft mode configuration
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091
      # Broker-to-broker communication
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      # Single node cluster settings
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - everything-network
      - everything-pipeline-network

  kafka-ui:
    image: kafbat/kafka-ui:latest
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: everything
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
    ports:
      - "8003:8080"
    networks:
      - everything-pipeline-network
    depends_on:
      - kafka

networks:
  everything-network:
    external: true
    name: everything-network
  everything-pipeline-network:
    driver: bridge
    name: everything-pipeline-network

volumes:
  kafka-data:
