services:
  service:
    image: swift:6.2
    volumes:
      - ..:/workspace:cached
      - ../../shared:/workspace/shared
    command: sleep infinity
    networks:
      - everything-network
      - everything-order-network
    privileged: true
  cache:
    image: valkey/valkey:9-alpine
    volumes:
      - cache-data:/data
    # ports:
    #   - "6379:6379"
    networks:
      - everything-order-network
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: order
      POSTGRES_USER: order
      POSTGRES_PASSWORD: password
    # ports:
    #   - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - everything-order-network

networks:
  everything-network:
    external: true
    name: everything-network
  everything-order-network:
    driver: bridge
    name: everything-order-network

volumes:
  db-data:
  cache-data:
